[package]
name = "findomain"
version = "0.2.0"
authors = ["Eduard Toloza <tolosaeduard@gmail.com>"]
edition = "2018"
description = "A cross-platform tool that use Certificate Transparency logs to find subdomains."
repository = "https://githut.com/edu4rdshl/findomain"
license = "GPL3"
keywords = ["certificate-transparency", "subdomain-discover", "find-subdomains", "subdomain-tool", "find-subdomain"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_derive = "1.0.90"
reqwest = "0.9.14"
trust-dns-resolver = "0.10.3"
clap = {version = "2.33.0", features = ["yaml"]}
lazy_static = "1.3.0"
rand = "0.7.0"
url = "2.0.0"
# json = "0.11.14"

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
