[package]
name = "findomain"
version = "1.3.0-rc.1"
authors = ["Eduard Tolosa <edu4rdshl@protonmail.com>"]
edition = "2018"
description = "The fastest and cross-platform subdomain enumerator, don't waste your time."
repository = "https://github.com/edu4rdshl/findomain"
license = "GPL-3.0-or-later"
keywords = ["discover-subdomains", "ct-logs", "search-subdomains", "enumerate-subdomains", "subdomain-scanner"]
readme = "README.md"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "z"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.104"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
trust-dns-resolver = { version = "0.19.2", features = ["dns-over-rustls"] }
clap = { version = "2.33.0", features = ["yaml"] }
lazy_static = "1.4.0"
rand = "0.7.3"
postgres = "0.17.0"
failure = "0.1.6"
rayon = "1.3.0"

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.27", features = ["vendored"] }

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.27", features = ["vendored"] }
